# Generated by Django 6.0.5 on 2026-06-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_deposit_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
