# Generated by Django 6.0.5 on 2026-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_deposit_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rentcast_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
