# Generated by Django 6.0.5 on 2026-06-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_rentcast_id_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rentcast_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
