# Generated by Django 6.0.5 on 2026-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_property_image_alter_property_rentcast_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
